#
# (C) Copyright IBM Corp. 2021, 2021
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
appVersion: "1.0"
description: Quality Measure and Cohort Stack
name: cohort-stack
version: 1.0.0

dependencies:
  - name: cohort
    condition: cohort.enabled
  - name: spark-history-server
    condition: spark-history-server.enabled
